### ISSUE TITLE
Overlay Inspiration Card: Part 3 - Share Button

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#11]
**This issue requires that [Overlay Inspiration Card: Part 2 - Display](https://github.com/pariyatti/patta/issues/4) is finished first.**

- [ ] a simple working implementation will just use the same "share" functionality as the Stacked Inspiration Cards
- [ ] a more difficult implementation (try it!) will render the text onto the image and share the image-with-overlaid-text as it is displayed in the app. This will require a bit of image manipulation in Flutter.

**Comment by NamanShergill** [comment]
Fixed in #54

**Comment by deobald** [comment]
We'll leave this issue open until https://github.com/pariyatti/mobile-app/pull/54 is merged.

**Comment by deobald** [comment]
Closing this issue as it's actually been done since February. (Apologies for ignoring this project wall.)
