### ISSUE TITLE
Android Play Store: fix 404s for internal testers that is observed when someone has already joined the beta track for Pariyatti app

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#110]

**Comment by balwa** [comment]
The way we resolve this is by closing/pausing two tracks. The internal testing track enables us to create and manage internal testing releases to make the app available to up to 100 internal testers. It's more than sufficient at this point. And having four tracks just adds to overhead of releasing it to four tracks.

One closed testing track is closed and open testing track is paused. So similar to test flight, we release internally and we release it to the public.

**Active**
<img width="648" alt="Internal_testing_trac" src="https://user-images.githubusercontent.com/4284516/233767687-e369051e-2d0a-45dd-95e5-c86fd85ed3b8.png">

**Stopped track**
<img width="685" alt="Closed_testing_track" src="https://user-images.githubusercontent.com/4284516/233767690-4104c007-29d1-46ef-8b92-07d13c691c8f.png">

**Paused track***
<img width="771" alt="Open_testing_Paused" src="https://user-images.githubusercontent.com/4284516/233767691-4a994213-3b6e-48b0-bc40-693ac7864f18.png">

**Comment by balwa** [comment]
this means the android release documentation needs to be updated to reflect the new workflow
