### ISSUE TITLE
User-friendly Sharing

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#38]
- [ ] user should not be able to share an image that hasn't loaded yet (inspiration cards)
- [ ] clicking "share" should not require an additional network call to get images
- [ ] reuse the "share image" logic between stacked and overlay inspiration cards?

**Comment by NamanShergill** [comment]
Fixed in #54

**Comment by deobald** [comment]
Keeping this issue open until #54 is merged.

**Comment by NamanShergill** [comment]
Should I close this issue now?

**Comment by NamanShergill** [comment]
Sorry for the mislabel, I am a bit clumsy today

**Comment by deobald** [comment]
Closing. Handled by https://github.com/pariyatti/mobile-app/pull/54
