### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#51]
We should implement Sankalp's dark mode colour scheme before the v1 release.

- [ ] dark mode colors as per [Sankalp's color chart](https://github.com/pariyatti/agga/issues/4)
- [ ] manual light / dark mode switch
- [ ] option for automatic switching based on OS preferences

**Comment by VarunBarad** [comment]
Direct link to translation of colors between light and dark schemes
https://github.com/pariyatti/agga/issues/4#issuecomment-707551764

**Comment by deobald** [comment]
This seems easy enough to do without adding any extra packages:

https://github.com/JohannesMilke/theme_example
https://www.youtube.com/watch?v=HSAa9yi0OMA

**Comment by deobald** [comment]
Notes:

* footer icons are at 50% opacity for both light/dark modes
* @iamsankalp will create light/dark wireframes for Settings and Language screens
* @iamsankalp will provide a "brown" / ochre variation of dark mode on this GH issue

**Comment by deobald** [comment]
Basic dark mode is now in master
