### ISSUE TITLE
Audio button should return to "play" after MP3 stops

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#66]
Clicking the "stop" button then returns it to "play" mode, but it should do this on its own when the MP3 signals it has finished playing.

**Comment by deobald** [comment]
Fixed in https://github.com/pariyatti/mobile-app/commit/ed818852b86009f71b87090b1b98985ac25a2e71

**Comment by GitHubAnatta** [comment]
Oho. Sorry.
Still learning...
bit delayed due to other unexpected tasks.
Metta.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by deobald** [comment]
No problem at all! I happened to be in the code today and this was an
easier fix than I was expecting. :)

With Metta,
-steven

**Comment by GitHubAnatta** [comment]
🙏

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GitHubAnatta** [comment]
Dear Pariyatti /Steven,

I owe more than an apology.
For various reasons, could not keep up my words.
Yes, the learning got slow.
But not given up.
Hopefully I will get back soon to you.

Metta.
Kimd regards,
Kumar
~
________________________________

**Comment by deobald** [comment]
Hello Kumar,

No apology is required at all. Please feel free to continue monitoring the project's progress on GitHub and Discord while you learn ... and please do not feel rushed in any way. This project will still be here in six months or six years, so there are no time constraints on observation or contribution. :)

I wish you the best of luck with your practice and studies.

With Metta,
-steven

**Comment by GitHubAnatta** [comment]
Pranams Steven.
Metta.
Kumar
+

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
