### ISSUE TITLE
Apple App Store Connect API

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#77]
Unfortunately, although we can now create API keys, only the Account Holder can request access to the Connect API, as per the attached screenshot.

![Image](https://user-images.githubusercontent.com/20282/172000392-58449d83-4997-4886-a069-54c5459b5d19.png)

* go to https://appstoreconnect.apple.com/access/api
* click "Keys"
* click "App Store Connect API"
* click "Request Access"

**Comment by brihas** [comment]
Please try now. When I Requested Access I agreed to the polices below. Please confirm that we are abiding by these policies:

![Screen Shot 2022-06-06 at 12 43 12 PM](https://user-images.githubusercontent.com/953256/172236049-bd28e3e3-68a3-4977-9cd1-6802559263c4.png)

**Comment by deobald** [comment]
I received this reply from a helpful Codemagic engineer (who said it was okay to repost this). His explanation makes a lot of sense:

> Hi [@Steven Deobald](https://codemagicio.slack.com/team/U03JS8YSWAY), let me try to shed some light on the way that Codemagic handles user secrets as I believe this will help to dispel your concerns.
> 
> In order to use App Store (or any other) credentials, you have to store them somewhere on the machine that is doing the app building and signing. Since these secrets are necessary and need to be used for the build process to succeed, you necessarily need to make them available. When using Codemagic, the only difference is that you do not own the machine where the app is being build but you lease it for a limited time.
> 
> What is important to note is that configuring sensitive values in Codemagic UI (as explained here: https://docs.codemagic.io/variables/environment-variable-groups/#storing-sensitive-valuesfiles) does not give us the access to them. When you check the 'Secure' option while storing the environment variables, they are immediately encrypted and Codemagic does not have access to them. They are transferred encrypted to the build VM during the build process, decrypted and made available there during the build and then the whole VM gets destroyed afterwards.
> 
> Since the API key is being used to build your own app, in your own development workflow and you are not using it to provide build services for other people/companies, you are not in violation of Apple's policy.

Here is the original Slack thread: https://codemagicio.slack.com/archives/CEKE2KZ37/p1654645429330889

I'm satisfied with this explanation, but I will wait for @brihas and @balwa to close this issue.

**Comment by deobald** [comment]
@balwa is busy this week helping his Mom recover from surgery. Since I doubt he'll have any disagreements with the way we're using the Connect API, I'm going to close this issue. If we need to, we can always re-open it.

I've tested the API Key creation and it works.

**Comment by balwa** [comment]
Yes, would be a little occupied this week🙂 

The fact that there is at rest and in transit encryption and the machine is also recycled after the build gets done are acceptable measures to ensure that our api key remains private to the team. Also our automation workflows will be publishing the app to test flight for our internal users of the app to test. So, we should be good.
