### ISSUE TITLE
Create www.pariyatti.app website

### ISSUE THREAD

**Issue by deobald** [pariyatti/mobile-app#91]
* [x] link to App Store and Play Store
* [x] turn varun's designs into HTML
* [x] add "contributors" page
* [x] redirect `pariyatti.app` DNS to GitHub Pages

**Comment by balwa** [comment]
https://pariyatti.app/ is published using A records to 
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
